version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: vulnerable-application
      POSTGRES_PASSWORD: vulnerable-application
      POSTGRES_DB: vulnerable-application
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  vulnerable-application-be:
    build:
      context: ../../../
      dockerfile: ./support/docker/vulnerable-application-be/Dockerfile
    image: vulnerable-application-be:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vulnerable-application
    depends_on:
      - postgres
    restart: unless-stopped